/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.container}>
        <div className={styles.herocontainer}>
          <div className={styles.home}>
            <h1 className={styles.heroText1}>Welcome</h1>
            <h2 className={styles.heroText2}>To My Portfolio Page</h2>
          </div>
        </div>
        <div className={styles.section}>
          <section className={styles.section1}>
            <h1 className={styles.section1Heading}>Skills</h1>
            <div className={styles.slider}>
              <div className={styles.slideTrack}>
                <div className={styles.slide}>
                  <img
                    src="https://www.svgrepo.com/show/303205/html-5-logo.svg"
                    alt="Html"
                  />
                </div>
                <div className={styles.slide}>
                  <img
                    src="https://www.svgrepo.com/show/303481/css-3-logo.svg"
                    alt="CSS"
                  />
                </div>
                <div className={styles.slide}>
                  <img
                    src="https://www.svgrepo.com/show/303206/javascript-logo.svg"
                    alt="Java Script"
                  />
                </div>
                <div className={styles.slide}>
                  <img
                    src="https://www.svgrepo.com/show/303600/typescript-logo.svg"
                    alt="TypeScript"
                  />
                </div>
                <div className={styles.slide}>
                  <img
                    src="https://nodejs.org/static/images/logos/nodejs-new-pantone-black.svg"
                    alt="Node Js"
                  />
                </div>
                <div className={styles.slide}>
                  <img
                    src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9Ii0xMS41IC0xMC4yMzE3NCAyMyAyMC40NjM0OCI+CiAgPHRpdGxlPlJlYWN0IExvZ288L3RpdGxlPgogIDxjaXJjbGUgY3g9IjAiIGN5PSIwIiByPSIyLjA1IiBmaWxsPSIjNjFkYWZiIi8+CiAgPGcgc3Ryb2tlPSIjNjFkYWZiIiBzdHJva2Utd2lkdGg9IjEiIGZpbGw9Im5vbmUiPgogICAgPGVsbGlwc2Ugcng9IjExIiByeT0iNC4yIi8+CiAgICA8ZWxsaXBzZSByeD0iMTEiIHJ5PSI0LjIiIHRyYW5zZm9ybT0icm90YXRlKDYwKSIvPgogICAgPGVsbGlwc2Ugcng9IjExIiByeT0iNC4yIiB0cmFuc2Zvcm09InJvdGF0ZSgxMjApIi8+CiAgPC9nPgo8L3N2Zz4K"
                    alt="React"
                  />
                </div>
                <div className={styles.slide}>
                  <img
                    src="https://seeklogo.com/images/N/next-js-logo-7929BCD36F-seeklogo.com.png"
                    alt="Next Js"
                  />
                </div>
                <div className={styles.slide}>
                  <img
                    src="https://www.svgrepo.com/show/373482/c.svg"
                    alt="C"
                  />
                </div>
                <div className={styles.slide}>
                  <img
                    src="https://www.svgrepo.com/show/373528/cpp3.svg"
                    alt="C++"
                  />
                </div>
                <div className={styles.slide}>
                  <img
                    src="https://www.svgrepo.com/show/354238/python.svg"
                    alt="Python"
                  />
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};

export default Home;
