import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Project.module.css";
import css from "styled-jsx/css";
import Cards from "../components/Cards";

const Project = (props: any) => {
  return (
    <>
      <Head>
        <title>Porject</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Cards />
    </>
  );
};

export default Project;
